# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/prueba3',
                'doc_host': 'https://Itzelep.github.io',
                'git_url': 'https://github.com/Itzelep/prueba3',
                'lib_path': 'prueba3'},
  'syms': {'prueba3.core': {'prueba3.core.foo': ('core.html#foo', 'prueba3/core.py')}}}
